# Generated by Django 5.2 on 2025-05-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cv',
            field=models.FileField(default=None, upload_to='csv/'),
            preserve_default=False,
        ),
    ]
